[build]
  command = "npm run build"
  publish = ".next"

[context.production]
  environment = { NETLIFY_IDENTITY_ENABLED = "true" }

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200
